name: OpenAI Tests

# Only run these tests for master because they require an openai api key
on:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: jiro4989/setup-nim-action@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        nimble test -y
        nimble test --gc:orc -y
        nim c -r examples/example.nim
        nim c -r examples/streaming.nim
